### ISSUE TITLE
WFC not working correctly in latest Chrome

### ISSUE THREAD

**Issue by exus69** [unindented/whitelist-manager#4]
Hello,

When I try to visit a non-whitelisted url instead of showing that the site is blocked
it shows a blank page with "about:blank" written on the address bar. Seems like this issue has cropped up after updating chrome. Please check into the same and revert.

Thank You.

Best Regards,

exus69

**Comment by GUTHTIRE** [comment]
Hello,

Same issue as #4, non-whitelisted URL shows about:blank. Please help!

**Comment by unindented** [comment]
@GUTHTIRE @exus69 I've pushed a new version to the Chrome Web Store. You should see the issue fixed in the next few hours.
