### ISSUE TITLE
Way to export sites?

### ISSUE THREAD

**Issue by paulri** [unindented/whitelist-manager#5]
I will be maintaining this extension on at least 3 computers. It woudl be great if there were a way to quickly export and then import the sites whitelisted. Is this a possibility for the future? 

Regardless, thanks. this extension does a very good job and whitelisting. I've tried other solutions, but they always got in the way by continually asking for permission, etc. This allows anything on a whitelisted domain--very handy.

**Comment by unindented** [comment]
With the latest version, 2.0, your configuration will be synchronized across all computers where you are signed in:

![screen shot 2016-03-22 at 14 29 46](https://cloud.githubusercontent.com/assets/69485/13954896/938c781e-f03a-11e5-9b8b-bc8250cbce0c.png)
