### ISSUE TITLE
Whitelist Manager

### ISSUE THREAD

**Issue by lifestills** [unindented/whitelist-manager#57]
I installed the whitelist extension for chrome. I have added a list of websites that I want to allow but some of them are still not being allowed. Example: wikipedia and pbskids.org. I have listed them as allowed websites but whitelist manager is still blocking them. I don't understand why.

**Comment by unindented** [comment]
Thanks for reporting @lifestills. Can you share a screenshot of your configuration?

**Comment by lifestills** [comment]
I finally figured it out Nd its working now. Thanks.

**Comment by unindented** [comment]
Awesome!
