### ISSUE TITLE
Options.html:  Hitting enter after typing in a website resets the list instead of adding an entry.

### ISSUE THREAD

**Issue by MaulingMonkey** [unindented/whitelist-manager#6]
Extremely confusing behavior (I guess #options_reset ends up as the default submit button?), at first it looked like it was simply failing to add the website.  This seems to fix it (using native Javascript as I don't know coffeescript:)

```javascript
var filter = document.getElementById('filter_new');
filter.addEventListener('keypress', function(event) {
    if (event.keyCode == 13) {
        event.preventDefault();
        document.getElementById('filter_add').click();
    }
});
```

May want to change #options_save 's type to submit so enter without #filter_new focused doesn't accidentally do the same confusing thing...

**Comment by unindented** [comment]
@MaulingMonkey I've pushed a new version to the Chrome Web Store. In this new version entries are added in a simple textarea, so your problem should go away.
