### ISSUE TITLE
about:blank

### ISSUE THREAD

**Issue by tobydjones** [unindented/whitelist-manager#9]
If I go to a site that is not whitelisted, I do not see a message, I only get a blank page (about:blank).
I have only got the default three entries in my whitelist.

(Chrome Version 43.0.2357.124 m)

**Comment by unindented** [comment]
Thanks for reporting. Probably something has changed for Chrome extensions in latest Chrome versions. I'll look into this.

**Comment by unindented** [comment]
Same issue: https://github.com/unindented/whitelist-chrome/issues/4

**Comment by GUTHTIRE** [comment]
Any update on this one? Was hoping for a more polished message instead of "about:blank".

**Comment by unindented** [comment]
@GUTHTIRE yes, I'm working on it.

**Comment by unindented** [comment]
@tobydjones @GUTHTIRE I've pushed a new version to the Chrome Web Store. You should see the issue fixed in the next few hours.
